name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

# 更新权限配置
permissions:
  contents: write
  packages: write
  actions: write
  security-events: write
  deployments: write
  issues: write
  pages: write
  pull-requests: write
  repository-projects: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Verify Required Files
      run: |
        if not exist "mail_sender.py" (
          echo "Error: mail_sender.py not found"
          exit 1
        )
        if not exist "imgs\logo.ico" (
          echo "Error: imgs/logo.ico not found"
          exit 1
        )
        if not exist "styles.py" (
          echo "Error: styles.py not found"
          exit 1
        )

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed `
          --add-data "imgs;imgs" `
          --add-data "styles.py;." `
          --icon=imgs/logo.ico `
          --name email-sender `
          mail_sender.py
        
    - name: Verify Build
      run: |
        dir dist
        if not exist "dist\email-sender.exe" (
          echo "Build failed - executable not found"
          exit 1
        )
        
    - name: Create Release ZIP
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd dist
        dir
        7z a -tzip ../email-sender-${{ github.ref_name }}.zip *
        cd ..
        dir
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        name: 邮件批量发送工具 ${{ github.ref_name }}
        files: |
          email-sender-${{ github.ref_name }}.zip
          dist/email-sender.exe
          README.md
          CHANGELOG.md
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: email-sender
        path: |
          dist/email-sender.exe
          README.md
          requirements.txt
        retention-days: 90 